version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    container_name: backend
    volumes:
       - ./backend:/usr/src/app/frontend
       - /usr/src/app/backend/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "4200:4200"
    container_name: frontend
    volumes:
       - ./frontend:/usr/src/app/frontend
       - /usr/src/app/frontend/node_modules