version: "2"
services:
    balancer:
        image: "nginx"
        volumes:
            - ./nginx/:/etc/nginx:ro
        links:
            - node1:node1
            - node2:node2
        ports:
            - "80:80"
            - "443:443"

    node1:
        image: "node:6"
        hostname: "node1"
        volumes: 
            - ../ha-docker-node/:/usr/src/app
        expose: 
            - "3000"
        ports: 
            - "3001:3000"
        entrypoint: 
            - "/usr/local/bin/npm" 
            - "run" 
            - "start"
        working_dir: /usr/src/app
        cpu_quota: 25000
    
    node2:
        image: "node:6"
        hostname: "node2"
        volumes: 
            - ../ha-docker-node/:/usr/src/app
        expose: 
            - "3000"
        ports: 
            - "3002:3000"
        entrypoint: 
            - "/usr/local/bin/npm" 
            - "run" 
            - "start"
        working_dir: /usr/src/app
        cpu_quota: 25000